/*
 * File: app/store/Places.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.store.Places', {
    extend: 'Ext.data.Store',

    requires: [
        'MyApp.model.Place'
    ],

    config: {
        data: [
            {
                id: 1,
                name: 'Alcatraz',
                location: 'California',
                lat: 37.826641,
                lng: -122.422855
            },
            {
                id: 2,
                name: 'Four Corners Monument',
                location: 'USA',
                lat: 36.999091,
                lng: -109.045279
            },
            {
                id: 3,
                name: 'Golden Gate Bridge',
                location: 'San Francisco',
                lat: 37.816497,
                lng: -122.478175
            },
            {
                id: 4,
                name: 'Grand Canyon',
                location: 'Arizona',
                lat: 36.071302,
                lng: -111.874237
            },
            {
                id: 5,
                name: 'Las Vegas',
                location: 'Nevada',
                lat: 36.113749,
                lng: -115.173512
            },
            {
                id: 6,
                name: 'Monument Valley',
                location: 'Arizona',
                lat: 36.996658,
                lng: -110.097785
            },
            {
                id: 7,
                name: 'New York City',
                location: 'New York',
                lat: 40.726446,
                lng: -74.006767
            },
            {
                id: 8,
                name: 'Washington',
                location: 'District of Columbia',
                lat: 38.895225,
                lng: -77.036694
            },
            {
                id: 9,
                name: 'Wine tasting',
                location: 'Calistoga, California',
                lat: 38.578299,
                lng: -122.577653
            }
        ],
        model: 'MyApp.model.Place',
        storeId: 'Places',
        proxy: {
            type: 'ajax',
            reader: {
                type: 'json'
            }
        }
    }
});