/*
 * File: app/view/PlaceDetail.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.PlaceDetail', {
    extend: 'Ext.form.Panel',

    config: {
        id: 'PlaceDetail',
        items: [
            {
                xtype: 'fieldset',
                title: 'Details',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Place',
                        name: 'name'
                    },
                    {
                        xtype: 'textfield',
                        label: 'Location',
                        name: 'location'
                    }
                ]
            },
            {
                xtype: 'hiddenfield',
                id: 'lat',
                name: 'lat'
            },
            {
                xtype: 'hiddenfield',
                id: 'lng',
                name: 'lng'
            },
            {
                xtype: 'button',
                action: 'ViewMap',
                centered: false,
                margin: '20px',
                ui: 'forward',
                text: 'View on Map'
            }
        ]
    }

});